languageCode = "en-us"
title = "Sujith Quintelier"
theme = ["github.com/sujithq/ideal-octo-guacamole"]
resourceDir = "../resources"
baseURL = "http://localhost:1313/"

# Default behavior: exclude drafts and future posts
buildDrafts = false
buildFuture = false

[params]
  description = "Azure, cloud, and tech blog by Sujith Quintelier. Find tutorials, guides, and insights on GitHub, Azure, Terraform, DevOps, and more."
  tags = ['Azure', 'GitHub', 'Blog', 'Resume', 'Sujith', 'Quintelier', 'sujithq', 'DevOps']
  twitter = "@sujithq"
  themeColor = "#6a1d57"
  socialImage = "images/Sujith_Quintelier.jpg"
  author = "Sujith Quintelier"
  prismjsTheme = "solarizedlight" # coy dark funky okaidia solarizedlight tomorrow twilight

[params.days]
  new = 7       # Days threshold for "New" label
  updated = 14  # Days threshold for "Updated" label

[params.widgets]
  [params.widgets.archives]
    enabled = true
    limit = 5
  [params.widgets.about]
    enabled = true
  [params.widgets.taxonomy]
    enabled = true
  [params.widgets.recentPosts]
    enabled = true
  [params.widgets.subscribe]
    enabled = true

[permalinks]
  posts = "/posts/:year/:month/:slug"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'

[taxonomies]
  categories = 'categories'
  tags = 'tags'
  series = 'series'

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^HUGO_TESTING$']

[menu]
 [[menu.main]]
   identifier = "resume"
   name = "Resume"
   url = "/resume"
   weight = 1

 [[menu.main]]
   identifier = "archives"
   name = "Archives"
   url = "/posts"
   weight = 2

 [[menu.main]]
   identifier = "taxonomy"
   name = "Taxonomy"
   weight = 3
 [[menu.main]]
   identifier = "tags"
   name = "Tags"
   url = "/tags"
   weight = 1
   parent = "taxonomy"
 [[menu.main]]
   identifier = "categories"
   name = "Categories"
   url = "/categories"
   weight = 2
   parent = "taxonomy"
 [[menu.main]]
   identifier = "series"
   name = "Series"
   url = "/series"
   weight = 3
   parent = "taxonomy"

 [[menu.main]]
   identifier = "tools"
   name = "Tools"
   weight = 4
 [[menu.main]]
   identifier = "cidr-calculator"
   name = "CIDR Calculator"
   url = "/tools/cidr-calculator"
   weight = 1
   parent = "tools"
 [[menu.main]]
   identifier = "cert-renewal"
   name = "Azure Certification Renewal"
   url = "/tools/cert-renewal"
   weight = 2
   parent = "tools"
 [[menu.main]]
   identifier = "tech-radar"
   name = "Tech Radar"
   url = "/tools/tech-radar"
   weight = 3
   parent = "tools"

[services]
    [services.disqus]
    shortname = 'sujithq'

[pagination]
  disableAliases = false
  pagerSize = 4
  path = 'page'

[frontmatter]
  lastmod = ["lastmod", "git", "date"]

[build]
  [build.buildStats]
    enable = true
