main:
  - name: Contact
    url: /#contact
    weight: 30
  - name: CV
    identifier: CV
    url: /cv
    weight: 20
  - name: Biography
    url: /cv/#about
    weight: 10
    parent: CV
  - name: Experience
    url: /cv/#experience
    weight: 20
    parent: CV
  - name: Accomplishments
    url: /cv/#accomplishments
    weight: 21
    parent: CV
  - name: Badges
    url: /cv/#badges
    weight: 22
    parent: CV
