# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  # theme_day: minimal
  theme_night: minimal
  font: mr_robot
  font_size: L
  body_font: mr_robot
  heading_font: mr_robot
  nav_font: mr_robot
  mono_font: mr_robot

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Sujith: IT veteran with over 23 years in the industry, boasting a robust background as a Certified Azure Solutions Architect. Expert in designing secure, scalable, and reliable Azure solutions, with advanced knowledge in IT operations, cybersecurity, and Azure services. Complemented by a myriad of other certifications, Sujith stands as a testament to dedication and expertise in the realm of Azure architecture. Explore his detailed CV to grasp the depth of his skillset and achievements.'
    twitter: 'sujithq'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Sujith Quintelier.'
    license:
      enable: false
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: '1 Jan, 2023'
  time_format: '14:04'
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    theme_light: github-light
    theme_dark: dracula
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/sujithq/sujithq.github.io'
    content_dir: content
    branch: main
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
