# [development]
#   baseURL = "http://localhost:1313/"
#   disableRobotsTXT = true
#
# [production]
#   baseURL = "/"
#   disableRobotsTXT = false
#
# languageCode = 'en-us'
# LanguageDirection = 'ltr'
# title = 'Ideal Octo Guacamole'

[params]
  theme = "light"
  themes = ["dark", "light"]
  dateFormat = "Jan 2, 2006"

[[params.socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/sujithquintelier/"
  icon = "bi bi-linkedin"

[[params.socials]]
  name = "github"
  url = "https://github.com/sujithq/"
  icon = "bi bi-github"

[[params.socials]]
  name = "twitter"
  url = "https://x.com/SujithQ/"
  icon = "bi bi-twitter-x"

[[params.socials]]
  name = "mastodon"
  url = "https://mastodon.com/in/sujithq/"
  icon = "bi bi-mastodon"

[[params.socials]]
  name = "bsky"
  url = "https://bsky.app/profile/sujithq.bsky.social/"
  icon = "fa-brands fa-bluesky"

[[params.socials]]
  name = "facebook"
  url = "https://www.facebook.com/sujith.quintelier/"
  icon = "bi bi-facebook"

[[params.socials]]
  name = "instagram"
  url = "https://www.instagram.com/sujithquintelier/"
  icon = "bi bi-instagram"

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.145.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"
