# Hugo Configuration
languageCode = 'en-us'
title = 'Sujith Quintelier'
baseURL = 'http://localhost:1313/'
theme = ["github.com/sujithq/ideal-octo-guacamole"]

[params]
  theme = "light"
  themes = ["dark", "light"]
  dateFormat = "Jan 2, 2006"
  isLocal = false

[params.widgets]
  [params.widgets.archives]
    enabled = true
    limit = 5
  [params.widgets.about]
    enabled = true
  [params.widgets.taxonomy]
    enabled = true
  [params.widgets.recentPosts]
    enabled = true
  [params.widgets.subscribe]
    enabled = true

[[params.socials]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/sujithquintelier/"
  icon = "fab fa-linkedin"

[[params.socials]]
  name = "github"
  url = "https://github.com/sujithq/"
  icon = "fab fa-github"

[[params.socials]]
  name = "twitter"
  url = "https://x.com/SujithQ/"
  icon = "fab fa-x-twitter"

[[params.socials]]
  name = "mastodon"
  url = "https://mastodon.com/in/sujithq/"
  icon = "fab fa-mastodon"

[[params.socials]]
  name = "bsky"
  url = "https://bsky.app/profile/sujithq.bsky.social/"
  icon = "fa-brands fa-bluesky"

[[params.socials]]
  name = "facebook"
  url = "https://www.facebook.com/sujith.quintelier/"
  icon = "fab fa-facebook"

[[params.socials]]
  name = "instagram"
  url = "https://www.instagram.com/sujithquintelier/"
  icon = "fab fa-instagram"

[[params.socials]]
  name = "buymeacoffee"
  url = "https://www.buymeacoffee.com/sujithq"
  icon = "fab fa-buymeacoffee"

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.145.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"
