baseURL = "/"

[menu]

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"
    weight = 1

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/posts"
    weight = 2

 [[menu.main]]
   identifier = "taxonomy"
   name = "Taxonomy"
   weight = 3
 [[menu.main]]
   identifier = "tags"
   name = "Tags"
   url = "/tags"
   weight = 1
   parent = "taxonomy"
 [[menu.main]]
   identifier = "categories"
   name = "Categories"
   url = "/categories"
   weight = 2
   parent = "taxonomy"
 [[menu.main]]
   identifier = "series"
   name = "Series"
   url = "/series"
   weight = 3
   parent = "taxonomy"

 [[menu.main]]
   identifier = "tools"
   name = "Tools"
   weight = 4
 [[menu.main]]
   identifier = "cidr-calculator"
   name = "CIDR Calculator"
   url = "/tools/cidr-calculator"
   weight = 1
   parent = "tools"

[params]
  prismjsTheme = "okaidia"
