baseURL = "https://quintelier.dev/"

# Explicitly exclude drafts and future posts in production
buildDrafts = false
buildFuture = false

[menu]

  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "/resume"
    weight = 1

  [[menu.main]]
    identifier = "archives"
    name = "Archives"
    url = "/posts"
    weight = 2

 [[menu.main]]
   identifier = "taxonomy"
   name = "Taxonomy"
   weight = 3
 [[menu.main]]
   identifier = "tags"
   name = "Tags"
   url = "/tags"
   weight = 1
   parent = "taxonomy"
 [[menu.main]]
   identifier = "categories"
   name = "Categories"
   url = "/categories"
   weight = 2
   parent = "taxonomy"
 [[menu.main]]
   identifier = "series"
   name = "Series"
   url = "/series"
   weight = 3
   parent = "taxonomy"

 [[menu.main]]
   identifier = "tools"
   name = "Tools"
   weight = 4
 [[menu.main]]
   identifier = "cidr-calculator"
   name = "CIDR Calculator"
   url = "/tools/cidr-calculator"
   weight = 1
   parent = "tools"
 [[menu.main]]
   identifier = "cert-renewal"
   name = "Azure Certification Renewal"
   url = "/tools/cert-renewal"
   weight = 2
   parent = "tools"
 [[menu.main]]
   identifier = "tech-radar"
   name = "Tech Radar"
   url = "/tools/tech-radar"
   weight = 3
   parent = "tools"

  [[menu.main]]
    identifier = "updates"
    name = "Updates"
    url = "/updates"
    weight = 5

# [params]
#   prismjsTheme = "okaidia"

[services.disqus]
  shortname = 'sujithq'

[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'page'

[permalinks]
  posts = "/posts/:year/:month/:slug"
  # Hard switch: publish updates2 items under /updates/
  updates2 = "/updates/:slug/"
  # Move legacy updates (v1) to /updates-v1/ to avoid URL conflicts
  updates = "/updates-v1/:slug/"
