name: AI triage failed runs

on:
  workflow_run:
    workflows: ["Deploy to Github Pages", "Copilot Setup Steps", "build", "test", "ci"]
    types: [completed]

permissions:
  actions: read
  contents: read
  issues: write
  models: read

jobs:
  triage:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq unzip
      - name: Set vars
        id: vars
        run: |
          echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT
          echo "run_url=${{ github.event.workflow_run.html_url }}" >> $GITHUB_OUTPUT
          echo "repo=${{ github.repository }}" >> $GITHUB_OUTPUT
          echo "branch=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_OUTPUT
          echo "sha=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
      - name: Download logs (zip)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p logs
          curl -sSL -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ steps.vars.outputs.run_id }}/logs" \
            -o logs/run-logs.zip
          unzip -q logs/run-logs.zip -d logs
      - name: Download artifacts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p artifacts
          gh run download ${{ steps.vars.outputs.run_id }} --repo "${{ github.repository }}" --dir artifacts || echo "No artifacts"
          find artifacts -maxdepth 2 -type f | sed 's/^/- /' > artifacts_index.md || true
      - name: Build AI prompt
        id: prompt
        run: |
          echo "Failure in ${{ steps.vars.outputs.repo }} on branch ${{ steps.vars.outputs.branch }} at ${{ steps.vars.outputs.sha }}" > prompt.txt
          echo "Run: ${{ steps.vars.outputs.run_url }}" >> prompt.txt
          printf "\nGoal: Summarise failure cause and propose next steps. Keep it short.\n" >> prompt.txt
          printf "\nArtifacts (if any):\n" >> prompt.txt
          cat artifacts_index.md >> prompt.txt || true
          printf "\nLogs (head):\n" >> prompt.txt
          mapfile -t LOG_FILES < <(find logs -maxdepth 2 -type f | head -n 3)
          if [ ${#LOG_FILES[@]} -eq 0 ]; then echo "(no log files found under logs/)" >> prompt.txt; fi
          for f in "${LOG_FILES[@]}"; do
            echo "--- $f ---" >> prompt.txt
            head -n 60 "$f" >> prompt.txt || true
          done
          printf "\nLogs (tail):\n" >> prompt.txt
          for f in "${LOG_FILES[@]}"; do
            echo "--- $f ---" >> prompt.txt
            tail -n 60 "$f" >> prompt.txt || true
          done
      - name: Call GitHub Models (chat completions)
        id: ai
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          primary_model="openai/gpt-4o"
          fallback_model="openai/gpt-4o-mini"

          make_body() {
            jq -n \
              --arg model "$1" \
              --rawfile content prompt.txt \
              '{model: $model, messages: [{role:"system", content:"You are a senior CI engineer. Be concise."}, {role:"user", content:$content}]}'
          }

          # Try primary model first
          body=$(make_body "$primary_model")
          curl -sS https://models.github.ai/inference/chat/completions \
            -H "Authorization: Bearer $TOKEN" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d "$body" | tee response.json

          # If API returns an error field, retry once with fallback model
          if jq -e '.error' response.json >/dev/null 2>&1; then
            echo "Primary model ($primary_model) unavailable: $(jq -r '.error.message // .error.code // "unknown"' response.json)" >&2
            body=$(make_body "$fallback_model")
            curl -sS https://models.github.ai/inference/chat/completions \
              -H "Authorization: Bearer $TOKEN" \
              -H "Accept: application/json" \
              -H "Content-Type: application/json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d "$body" | tee response.json
          fi

          jq -r '.choices[0].message.content // empty' response.json > summary.md
          if [ ! -s summary.md ]; then echo "No AI summary produced" > summary.md; fi
      - name: Ensure labels exist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh label create "ci-failure" --repo "${{ github.repository }}" --color B60205 --description "CI pipeline failure" 2>/dev/null || true
          gh label create "needs-triage" --repo "${{ github.repository }}" --color D4C5F9 --description "Requires triage" 2>/dev/null || true
      - name: Create issue
        id: issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          title="CI failure: ${{ github.event.workflow_run.name }} on ${{ steps.vars.outputs.branch }}"
          body=$(printf "### AI summary\n\n%s\n\n---\n\nRun: %s\nCommit: %s\n\n> Prompt (truncated)\n\n\n" "$(cat summary.md)" "${{ steps.vars.outputs.run_url }}" "${{ steps.vars.outputs.sha }}")
          payload=$(jq -n --arg title "$title" --arg body "$body" '{title:$title, body:$body, labels:["ci-failure","needs-triage"]}')
          number=$(echo "$payload" | gh api -X POST "repos/${{ github.repository }}/issues" --input - --jq '.number')
          echo "number=$number" >> "$GITHUB_OUTPUT"

      - name: List possible assignees
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Assignees allowed in ${{ github.repository }}:" | tee -a "$GITHUB_STEP_SUMMARY"
          gh api "repos/${{ github.repository }}/assignees?per_page=100" --paginate --jq '.[].login' | sort -u | tee assignees.txt
          if [ -s assignees.txt ]; then
            {
              echo "";
              echo "### Possible assignees";
              sed 's/^/- /' assignees.txt;
            } >> "$GITHUB_STEP_SUMMARY"
          else
            echo "No assignees returned" | tee -a "$GITHUB_STEP_SUMMARY"
          fi
      - name: Optionally assign to Copilot coding agent
        if: ${{ true }} # set to true when Copilot coding agent is available
        env:
          GH_TOKEN: ${{ secrets.PAT_WITH_ISSUES_WRITE != '' && secrets.PAT_WITH_ISSUES_WRITE || secrets.GITHUB_TOKEN }}
          COPILOT_ACTOR: ${{ vars.COPILOT_ACTOR || secrets.COPILOT_ACTOR || '' }}
        run: |
          set -euo pipefail

          OWNER="${GITHUB_REPOSITORY%/*}"
          REPO="${GITHUB_REPOSITORY#*/}"
          ISSUE_NUM="${{ steps.issue.outputs.number }}"

          # Discover a Copilot-like actor (prefer bots)
          ACTORS=$(gh api graphql -f owner="$OWNER" -f name="$REPO" -f query='
            query($owner:String!,$name:String!) {
              repository(owner:$owner, name:$name) {
                suggestedActors(capabilities:[CAN_BE_ASSIGNED], first:100) {
                  nodes { login type: __typename id }
                }
              }
            }' || echo '{}')

          # First try bots with copilot/agent/swe in login, then any login with those terms
          BOT_ID=$(echo "$ACTORS" | jq -r '
            [.data?.repository?.suggestedActors?.nodes[]?
            | select(.type=="Bot" and (.login|test("copilot|agent|swe|coding|code"; "i")))
            | .id] | first // empty')

          if [ -z "$BOT_ID" ]; then
            BOT_ID=$(echo "$ACTORS" | jq -r '
              [.data?.repository?.suggestedActors?.nodes[]?
              | select(.login|test("copilot|agent|swe|coding|code"; "i"))
              | .id] | first // empty')
          fi

          if [ -z "$BOT_ID" ]; then
            echo "Copilot agent not suggested for assignment. Skipping."; exit 0
          fi

          # Resolve issue node ID
          ISSUE_Q=$(gh api graphql -f owner="$OWNER" -f name="$REPO" -f num="$ISSUE_NUM" -f query='
            query($owner:String!,$name:String!,$num:Int!) {
              repository(owner:$owner, name:$name) { issue(number:$num) { id } }
            }')
          ISSUE_ID=$(echo "$ISSUE_Q" | jq -r '.data.repository.issue.id // empty')
          [ -n "$ISSUE_ID" ] || { echo "Failed to resolve issue id."; exit 1; }

          # Add assignee (do not replace existing)
          gh api graphql -f id="$ISSUE_ID" -f actors="$BOT_ID" -f query='
            mutation($id:ID!,$actors:[ID!]!){
              addAssigneesToAssignable(input:{assignableId:$id, assigneeIds:$actors}) {
                assignable { __typename }
              }
            }'
